[package]
name = "untitled7"
version = "0.1.0"
authors = ["wangchao <watcher.hangzhou@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
